# Number of days of inactivity before an issue becomes stale
# Yes one week is enough as the past has shown that people will anyway not continue the work if they did not answer after that time.
daysUntilStale: 7
daysUntilClose: 21

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - ANNOUNCEMENT%20%3Ascream%3A
  - never-stale
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed soon. Please update it or it may be closed to keep our repository organized.
  The best way is to add some more information or make a pull request with a test case.
  Also you might get help in fixing it at the [RxDB Community Chat](https://rxdb.info/chat)
  If you know you will continue working on this, just write any message to the issue (like "ping") to remove the stale tag.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: "Issues are autoclosed after some time. If you still have a problem, make a PR with a test case or to prove that you have tried to fix the problem."


# https://github.com/probot/stale/blob/7510fac863900a98057436d308e9fe21bbe314ec/README.md?plain=1#L66
only: issues
